version: '2.2'

services:
  simulator:
    image: simulator:latest
    container_name: simulator
    environment:
      - "DISPLAY=host.docker.internal:0.0"
      - "LIBGL_ALWAYS_INDIRECT=0"
    volumes: 
      - "C:/github/suho/simulator/src:/home/dev_ws/src"
    command: >
      bash -c "tail -F anything"
    privileged: true
    restart: always
