version: '2.2'

networks:
  bridge-network:
    external: true

services:  
  ros-master:
    image: ros:noetic-ros-core
    container_name: ros-master
    command: stdbuf -o L roscore
    networks:
      bridge-network:
        ipv4_address: 192.168.56.2
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.2"
    restart: always

  rosbridge-suite:
    image: ghcr.io/suho0515/websocket:latest
    container_name: rosbridge-suite
    depends_on:
      - ros-master    
    command: >
      bash -c "roslaunch rosbridge_server rosbridge_websocket.launch"
    networks:
      bridge-network:
        ipv4_address: 192.168.56.3
    ports:
      - "9090:9090"
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.3"
    restart: always

  simple-publisher:
    image: ghcr.io/suho0515/websocket:python3
    container_name: simple-publisher
    depends_on:
      - ros-master    
    command: >
      bash -c "source ~/catkin_ws/devel/setup.bash && rosrun simple_publisher simple_publisher_node.py"
    networks:
      bridge-network:
        ipv4_address: 192.168.56.4
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.4"
    restart: always

  dev-container:
    image: ghcr.io/suho0515/websocket:python3
    container_name: dev-container
    depends_on:
      - ros-master
    networks:
      bridge-network:
        ipv4_address: 192.168.56.11
    ports:
      - "3000:3000"        
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.11"
      - "DISPLAY=host.docker.internal:0.0"
      - "LIBGL_ALWAYS_INDIRECT=0"
    volumes: 
      - C:\github\suho:/root/catkin_ws/src/suho
    command: >
      bash -c "tail -F anything"
    privileged: true
    restart: always